package pinhole

import java.net.InetAddress
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull

class ConnectionStringTest {

    // Generated by Pinhole.Net's own public ConnectionString API:
    //   peerId 0x0123456789ABCDEF, NatHint.Cone, Direct 192.168.1.42:51234,
    //   Reflexive 203.0.113.7:51234, static key 0x01..0x20, endpoint key 0x65..0x84.
    private val netVector =
        "pinhole1:AwPvzauJZ0UjAQECBMCoASrIIgEEywBxB8giAgECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5_gIGCg4Q"

    @Test
    fun parsesNetGeneratedVector() {
        val cs = ConnectionString.parse(netVector)
        assertEquals(0x0123456789ABCDEFuL, cs.peerId)
        assertEquals(NatHint.Cone, cs.natHint)
        assertEquals(2, cs.candidates.size)

        val direct = cs.candidates[0]
        assertEquals(CandidateKind.Direct, direct.kind)
        assertEquals(InetAddress.getByName("192.168.1.42"), direct.address.address)
        assertEquals(51234, direct.address.port)

        val reflexive = cs.candidates[1]
        assertEquals(CandidateKind.Reflexive, reflexive.kind)
        assertEquals(InetAddress.getByName("203.0.113.7"), reflexive.address.address)
        assertEquals(51234, reflexive.address.port)

        assertContentEquals(ByteArray(32) { (it + 1).toByte() }, cs.staticKey)
        assertContentEquals(ByteArray(32) { (it + 101).toByte() }, cs.endpointKey)
    }

    @Test
    fun toleratesWhitespaceAndOmittedScheme() {
        val cs = ConnectionString.parse("  ${netVector.substringAfter(':')} ")
        assertEquals(0x0123456789ABCDEFuL, cs.peerId)
    }

    @Test
    fun rejectsMalformedStrings() {
        assertFailsWith<IllegalArgumentException> { ConnectionString.parse("http://example.com") }
        assertFailsWith<IllegalArgumentException> { ConnectionString.parse("pinhole1:not base64!!") }
        assertFailsWith<IllegalArgumentException> { ConnectionString.parse("pinhole1:AAAA") }
    }

    @Test
    fun realTicketFromDotNetNodeParses() {
        // A live v3 ticket printed by OpusVoice.Receiver (relay URLs are transitory; the
        // structure and keys are what matter here).
        val ticket = readResourceText("/net-receiver-ticket.txt") ?: return // optional fixture
        val cs = ConnectionString.parse(ticket.trim())
        kotlin.test.assertNotNull(cs.staticKey)
        kotlin.test.assertNotNull(cs.endpointKey)
        kotlin.test.assertTrue(cs.candidates.isNotEmpty())
    }

    private fun readResourceText(name: String): String? =
        object {}.javaClass.getResource(name)?.readText()
}
